project:
  type: website
  output-dir: docs

website:
  title: "Sam and Tom had a wedding"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - route.qmd
      

format:
  html:
    theme: minty
    backgroundcolor: "#ece2d0"
    linkcolor: "#6d2e46"
    css: styles.css
    toc: true

editor: visual

