project:
  type: website
  output-dir: docs

website:
  title: "Sam and Tom had a wedding"
  navbar:
    background: "#B0C8F7"
    foreground: "#6d2e46"
    search: false
    left:
      - href: index.qmd
        text: Welcome
      - photos.qmd
      - route.qmd

      

format:
  html:
    theme: minty
    backgroundcolor: "#f7eee6"
    linkcolor: "#6d2e46"
    css: styles.css
    toc: true

editor: visual

